services:
  db:
    ports:
      - "5432:5432"

  web:
    build:
      args:
        INSTALL_DEV: "true"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "1"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  worker:
    volumes:
      - ./:/app
