# Generated by Django 5.1.15 on 2026-08-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_order_no', models.CharField(max_length=32, unique=True)),
                ('internal_order_no', models.CharField(blank=True, db_index=True, max_length=32)),
                ('carrier', models.CharField(blank=True, max_length=64)),
                ('tracking_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('shop_name', models.CharField(blank=True, max_length=64)),
                ('order_status', models.CharField(blank=True, max_length=64)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=64)),
                ('sales_staff', models.CharField(blank=True, max_length=128)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('subdistrict', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('shipping_imported_at', models.DateTimeField(blank=True, null=True)),
                ('detail_imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='customers.customer')),
            ],
            options={
                'db_table': 'crm_online_order',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('upsell_staff', models.CharField(blank=True, max_length=128)),
                ('upsell_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='online_orders.onlineorder')),
            ],
            options={
                'db_table': 'crm_online_order_line',
            },
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['-ordered_at', '-id'], name='ix_online_order_recent'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['customer', '-ordered_at'], name='ix_online_order_customer'),
        ),
        migrations.AddConstraint(
            model_name='onlineorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='ux_online_order_line_no'),
        ),
    ]
