# Generated by Django 5.1.15 on 2026-07-30 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('ALL', 'ทุกคน'), ('INDIVIDUAL', 'รายคน')], max_length=16)),
                ('status', models.CharField(choices=[('HOLIDAY', 'วันหยุด'), ('LEAVE', 'วันลา')], default='HOLIDAY', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_holiday',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='ix_holiday_date')],
            },
        ),
    ]
