# Generated by Django 5.1.15 on 2026-07-25 12:45

import crm.accounts.managers
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('EDITOR', 'EDITOR'), ('ADMIN', 'ADMIN'), ('พนักงาน', 'พนักงาน'), ('TELESELL', 'TELESELL'), ('STAFF', 'STAFF'), ('USER', 'USER'), ('ทั่วไป', 'ทั่วไป')], default='ทั่วไป', max_length=64)),
                ('staff_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('staff_name', models.CharField(blank=True, max_length=128)),
                ('owner_alias', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['staff_code'], name='ix_user_staff_code_active')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='ux_user_email_lower')],
            },
            managers=[
                ('objects', crm.accounts.managers.UserManager()),
            ],
        ),
    ]
