# Generated by Django 5.1.15 on 2026-07-26 01:31

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Explicit: nothing else depends on core.0001_extensions, so without
        # this the migration graph wouldn't guarantee btree_gist exists
        # before this migration's ExclusionConstraint needs it.
        ("core", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(choices=[('CRM_TEAM', 'CRM Team'), ('UPSELL_TEAM', 'Upsell Team')], max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_team_assignment',
                'indexes': [models.Index(fields=['user', '-effective_from'], name='ix_team_assignment_user_period'), models.Index(fields=['team_code', 'effective_from', 'effective_to'], name='ix_team_assignment_team_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_team_assignment_period'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('user',), name='ux_team_assignment_current_user'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('user', '='), (models.Func('effective_from', 'effective_to', function='tstzrange'), '&&')], name='ex_team_assignment_period')],
            },
        ),
    ]
