# Generated by Django 5.1.15 on 2026-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('product_group', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('sku_number', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=255)),
                ('archive_reason', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_product',
                'indexes': [models.Index(condition=models.Q(('archived_at__isnull', True)), fields=['is_active', 'sku_number', 'sort_order'], name='ix_product_live'), models.Index(condition=models.Q(('archived_at__isnull', False)), fields=['archived_at'], name='ix_product_archived')],
                'constraints': [models.UniqueConstraint(fields=('sku', 'product_group', 'product_name'), name='ux_product_sku_group_name')],
            },
        ),
        migrations.CreateModel(
            name='StaffOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(blank=True, max_length=32)),
                ('staff_name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_staff_option',
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'staff_name'], name='ix_staff_option_active_sort')],
            },
        ),
    ]
