# Generated by Django 5.1.15 on 2026-07-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('interested', 'interested'), ('follow_up', 'follow_up'), ('won', 'won'), ('lost', 'lost'), ('dormant', 'dormant')], default='new', max_length=32)),
                ('status', models.CharField(choices=[('none', 'none'), ('scheduled', 'scheduled'), ('round_1', 'round_1'), ('round_2', 'round_2'), ('round_3', 'round_3'), ('round_4', 'round_4'), ('done', 'done'), ('missed', 'missed')], default='none', max_length=32)),
                ('priority', models.CharField(choices=[('Super VIP', 'Super VIP'), ('VIP', 'VIP'), ('Premium', 'Premium'), ('Economy', 'Economy'), ('NEW', 'NEW'), ('Dismiss', 'Dismiss')], default='NEW', max_length=16)),
                ('priority_rank', models.SmallIntegerField(default=2, editable=False)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('staff_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('owner_display', models.CharField(blank=True, max_length=128)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='customers.customer')),
            ],
            options={
                'db_table': 'crm_followup',
                'indexes': [models.Index(fields=['staff_code', 'next_followup_date', '-priority_rank', 'id'], name='ix_followup_queue'), models.Index(fields=['next_followup_date', '-priority_rank', 'id'], name='ix_followup_queue_all'), models.Index(fields=['status', 'lead_status', 'priority_rank'], name='ix_followup_status'), models.Index(condition=models.Q(('status', 'done'), _negated=True), fields=['next_followup_date'], name='ix_followup_due_open')],
            },
        ),
    ]
