# Generated by Django 5.1.15 on 2026-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagingImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_batch_id', models.UUIDField()),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('url', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=32)),
                ('phone2', models.CharField(blank=True, max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True)),
                ('tracking_no', models.CharField(blank=True, max_length=64)),
                ('carrier', models.CharField(blank=True, max_length=64)),
                ('order_status', models.CharField(blank=True, max_length=64)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('staff_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('import_status', models.CharField(default='valid', max_length=16)),
                ('validation_error', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('sale_type', models.CharField(blank=True, max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_staging_import_row',
                'indexes': [models.Index(fields=['import_batch_id', '-uploaded_at'], name='ix_staging_batch_uploaded'), models.Index(fields=['order_id'], name='ix_staging_order_no')],
            },
        ),
    ]
