# Generated by Django 5.1.15 on 2026-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_key', models.CharField(max_length=64, unique=True)),
                ('phone1', models.CharField(blank=True, max_length=32)),
                ('phone2', models.CharField(blank=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('owner_display', models.CharField(blank=True, max_length=128)),
                ('staff_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_customer',
            },
        ),
    ]
