# Generated by Django 5.1.15 on 2026-07-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('imports', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.stagingimportrow'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['staff_code', '-last_order_date', '-id'], name='ix_customer_scope_recent'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-last_order_date', '-updated_at', '-id'], name='ix_customer_recent'),
        ),
    ]
