# Generated by Django 5.1.15 on 2026-08-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_subdistrict'),
        ('imports', '0003_importjob'),
        ('orders', '0002_remove_order_ix_order_revenue_staff_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='ix_customer_recent',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(models.OrderBy(models.F('last_order_date'), descending=True, nulls_last=True), models.OrderBy(models.F('updated_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='ix_customer_recent_nl'),
        ),
    ]
