# Generated by Django 5.1.15 on 2026-07-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=64)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('sale_type', models.CharField(choices=[('NEW_ORDER', 'NEW_ORDER'), ('UPSELL', 'UPSELL'), ('FOLLOW', 'FOLLOW')], default='NEW_ORDER', max_length=16)),
                ('order_status', models.CharField(blank=True, max_length=64)),
                ('carrier', models.CharField(blank=True, max_length=64)),
                ('tracking_no', models.CharField(blank=True, max_length=64)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('owner_display', models.CharField(blank=True, max_length=128)),
                ('staff_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('import_batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.stagingimportrow')),
            ],
            options={
                'db_table': 'crm_order',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.stagingimportrow')),
            ],
            options={
                'db_table': 'crm_order_line',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-order_date', '-id'], name='ix_order_customer_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('sale_type__in', ('NEW_ORDER', 'UPSELL'))), fields=['created_at', 'staff_code'], name='ix_order_revenue_staff'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('sale_type__in', ('NEW_ORDER', 'UPSELL'))), fields=['created_at', 'owner_display'], name='ix_order_revenue_owner'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='ix_order_uploaded_by_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['import_batch_id'], name='ix_order_batch'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_no', ''), _negated=True), fields=('order_no', 'customer'), name='ux_order_no_customer'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['sku'], name='ix_line_sku'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku', 'product_name'), name='ux_line_order_sku_name'),
        ),
    ]
