# Generated by Django 5.1.15 on 2026-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('imports', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='ix_order_revenue_staff',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='ix_order_revenue_owner',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('sale_type__in', ('NEW_ORDER', 'UPSELL'))), fields=['order_date', 'staff_code'], name='ix_order_revenue_staff'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('sale_type__in', ('NEW_ORDER', 'UPSELL'))), fields=['order_date', 'owner_display'], name='ix_order_revenue_owner'),
        ),
    ]
